DROP TABLE RECTANGULO;
DROP TABLE PUNTOS;
CREATE TABLE RECTANGULO(
RID    INTEGER NOT NULL PRIMARY KEY,
 XL    NUMBER,
 YL    NUMBER,
 XH    NUMBER,
 YH    NUMBER
)
/
CREATE TABLE PUNTOS(PID INTEGER NOT NULL PRIMARY KEY,
 X  NUMBER,
 Y NUMBER
);
/
INSERT INTO RECTANGULO VALUES(1, 0,0,2,2);
INSERT INTO RECTANGULO VALUES(2, 1,5,4,9);
INSERT INTO RECTANGULO VALUES(3, 5,6,8,7);
INSERT INTO RECTANGULO VALUES(4, 4,4,8,8);
INSERT INTO RECTANGULO VALUES(5, 5,1,7,2);
INSERT INTO RECTANGULO VALUES(6, 1,3,3,6);

INSERT INTO PUNTOS VALUES (1,1,1);
INSERT INTO PUNTOS VALUES (2,5,4);
INSERT INTO PUNTOS VALUES (3,6,10);
INSERT INTO PUNTOS VALUES (4,10,2);
INSERT INTO PUNTOS VALUES (5,4,6);
INSERT INTO PUNTOS VALUES (6,8,9);
INSERT INTO PUNTOS VALUES (7,3,7);
INSERT INTO PUNTOS VALUES (8,2,6);
INSERT INTO PUNTOS VALUES (9,7,1);
INSERT INTO PUNTOS VALUES (10,6,9);
COMMIT;
